[project]
name = "advent2025"
version = "0.1.0"
description = "Advent of Code 2025"
authors = [{ name = "Ryan Echols" }]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.5",
    "sympy>=1.14.0",
]
